-- require("plugins_config.colorscheme")
-- require("plugins_config.completions")
-- require("plugins_config.copilot")
require("plugins_config.gitsigns")
-- require("plugins_config.which_key")
-- require("plugins_config.mason")
-- require("plugins_config.lsp")
require("plugins_config.lualine")
require("plugins_config.nvimtree")
-- require("plugins_config.oil")
-- require("plugins_config.swagger-preview")
require("plugins_config.telescope")
require("plugins_config.treesitter")
-- require("plugins_config.vim-test")
