-- require("core.plugins_config.colorscheme")
-- require("core.plugins_config.completions")
-- require("core.plugins_config.copilot")
require("core.plugins_config.gitsigns")
require("core.plugins_config.which_key")
-- require("core.plugins_config.mason")
-- require("core.plugins_config.lsp_config")
require("core.plugins_config.lualine")
require("core.plugins_config.nvimtree_config")
-- require("core.plugins_config.oil")
-- require("core.plugins_config.swagger-preview")
require("core.plugins_config.telescope")
-- require("core.plugins_config.treesitter")
-- require("core.plugins_config.vim-test")
