# /etc/keyd/default.conf
#
# INSTALL
# -----------------------------------------------------------------------------
# git clone https://github.com/rvaiya/keyd
# cd keyd
# make && sudo make install
# sudo systemctl enable --now keyd
#
# NOTES
# -----------------------------------------------------------------------------
# It is possible to render your machine unusable with a bad config file.
# Should you find yourself in this position, the special key sequence
# backspace+escape+enter should cause keyd to terminate.
#
# Special/predefined sections:
# [ids] — device selection
# [main] — default layer
# [shift] — Shift layer
# [control] — Ctrl layer
# [alt] — Alt layer
# [meta] — Super/Windows layer
# [altgr] — AltGr layer
# [capslock] — Caps Lock layer
# [numlock] — Num Lock layer
#
# Custom layers:
# [nav]
# [caps_space]
# [emoji]
#
# overload(layer, key) = Temporarily activates a layer while the key is held,
#                        but sends another key if you tap it.
#
# layer(layer) = Activates a layer while the key is held.
#
# toggle(emoji) = tap ctrl → emoji layer active,
#                 tap ctrl again → emoji layer inactive.
#
#
# List keys for config `keyd.rvaiya list-keys`
#
# For testing key names:
# sudo keyd monitor
#
# Reload after changing this config
# sudo keyd reload
#
# gTile
# ------
# We have a Gnome extentie gTile configured to position screens.
# cat ~/gtd/scripts/gnome/gTile.conf | dconf load /org/gnome/shell/extensions/gtile/
# Used with combinations: Super+Alt+[0-9]
#
# Optimized for keyboards:
# Skyloong GK61 keyboard 60%
# TMKB T63 Gaming Wireless Keyboard 60%
# Aula F75 Pad 80%
# -------------------------------------
[ids]
*

[main]

# Maps capslock to escape when pressed and caps section when held.
capslock = overload(caps, esc)

# Aula F75 Pad Mechanisch Toetsenbord
# -----------------------------------
# This keyboard has no Right Ctrl, this key is needed for altgr-intl
# combination works, including the dead keys for €, à, ï, ñ and so on.
rightcontrol = rightalt

[shift]
# Shift + Capslock (de)activate Capslock
capslock = capslock
end = home

# Mistakes
backspace = noop


[alt]
# Position screen with gnome extention gTile.
1 = macro(M-A-f1)
2 = macro(M-A-f2)
3 = macro(M-A-f3)
4 = macro(M-A-f4)
5 = macro(M-A-f5)
6 = macro(M-A-f6)
7 = macro(M-A-f7)
8 = macro(M-A-f8)
9 = macro(M-A-f4)

[caps]
#------------------------------------------
# create a new layer with Capslock + Super
leftmeta = layer(caps_meta)

# create a new layer with Capslock + Alt
leftalt = layer(caps_alt)

# Create a new layer with Capslock + Space
space = layer(caps_space)
#------------------------------------------

# Navigation
h = left
j = down
k = up
l = right
u = pageup
d = pagedown

# Top/Home/End
t = home
e = end

i = insert

# print/screen
s = sysrq

# Laptop
b = brightnessdown
f = brightnessup

backspace = delete
q = macro(A-f4)

# Move window to other workspace
- = macro(S-M-A-left)
equal = macro(S-M-A-right)

[caps_meta]

# Function keys
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10

# Goto other workspace
h = macro(M-A-left)
l = macro(M-A-right)

[caps_alt]

# Move window to other workspace
h = macro(S-M-A-left)
l = macro(S-M-A-right)

[caps_space]

# Media
j = volumedown
k = volumeup
n = nextsong
b = previoussong
m = mute
p = playpause


# Unicodes/Emoji
#---------------
# Arrows ← →
h = macro(C-S-u 2 1 9 0 enter)
l = macro(C-S-u 2 1 9 2 enter)
# 😊
0 = macro(C-S-u 1 f 6 0 a enter)

