require("lazy").setup({
--  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
--  "tpope/vim-commentary",
--  "mattn/emmet-vim",
  "nvim-tree/nvim-tree.lua",
  "nvim-tree/nvim-web-devicons",
--  "echasnovski/mini.icons",
--  "ellisonleao/gruvbox.nvim",
--  "dracula/vim",
  "nvim-lualine/lualine.nvim",
  "nvim-treesitter/nvim-treesitter",
--  "vim-test/vim-test",
  "lewis6991/gitsigns.nvim",
--  "mg979/vim-visual-multi",
--  "tpope/vim-commentary",
  "mbbill/undotree",
--  "preservim/vimux",
--  "christoomey/vim-tmux-navigator",
--  "tpope/vim-fugitive",
--  "tpope/vim-surround",
--  "stevearc/oil.nvim",
--  -- completion
--  "hrsh7th/nvim-cmp",
--  "hrsh7th/cmp-nvim-lsp",
--  "L3MON4D3/LuaSnip",
--  "saadparwaiz1/cmp_luasnip",
--  "rafamadriz/friendly-snippets",
--  "github/copilot.vim",
--  "williamboman/mason.nvim",
--  "williamboman/mason-lspconfig.nvim",
--  "neovim/nvim-lspconfig",
--  {
--    "vinnymeller/swagger-preview.nvim",
--    run = "npm install -g swagger-ui-watcher",
--  },
  "nvim-telescope/telescope.nvim",
--  "folke/which-key.nvim",
})
